### ISSUE TITLE
Error Redirect URI

### ISSUE THREAD

**Issue by josemejiasji** [zyra/ngx-facebook#71]
Hi,

I'm facing an issue when I trigger the login. A new window opens and says: 

“URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings.”

What URI should I put on my app settings?

**Comment by ihadeed** [comment]
The URL of your app, example `https://mywebsite.com` or `http://localhost:8100`

**Comment by gonzag** [comment]
Hi @ihadeed, I have the same problem.
I'm running the server in https://localhost:443
I'm trying to call the login in:
https://localhost/upload
The popup: “URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings.” appears.

And in my facebook application, I set up these valid OAuth redirect URIs:
https://localhost/upload
https://localhost/
https://localhost:443/upload
https://localhost:443/
http://0.0.0.0:443/
http://0.0.0.0:443/upload
http://localhost/upload
http://localhost/

And the popup window url contains this:
redirect_uri=https://staticxx.facebook.com/connect/xd_arbiter/r/XBwzv5Yrm_1.js?version=42#cb=f14e3e14f7858fc&domain=localhost&origin=https://localhost/f267362313dc48

So, what I'm missing ? 
Where I can set up the redirection url ?
Thanks in advance.

**Comment by danielsogl** [comment]
Reopen the issue if you still have this problem.
